// Jiesa v 0.0.8a
(function(p,Y){var w=document||{},l=w.documentElement||{},q=l.addEventListener,G=/^[^{]+\{\s*\[native \w/,O=/callback\.call\(([^)]+)\)/g,r=function(a){return"string"===typeof a},y=function(a){return"function"===typeof a},H=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},I={BEFORE:"",COUNT:"a ? a.length : 0",BODY:"",AFTER:""},t=function(){return function(a){var b="%BEFORE%\nvar i=0,n=%COUNT%;for(;i<n;++i){%BODY%}%AFTER%",c;for(c in I)b=b.replace("%"+c+"%",a[c]||
I[c]);b=b.replace(O,function(a,b){return"(that?"+a+":callback("+b.split(",").slice(1).join()+"))"});return Function("a","callback","that","undefined",b)}}(),z=t({BODY:"callback.call(that, a[i], i, a)",AFTER:"return a"}),P=t({BEFORE:"var arr = []",BODY:"if (callback.call(that, a[i], i, a)) arr.push(a[i])",AFTER:"return arr"}),Q=t({BEFORE:"var arr = Array(a && a.length || 0)",BODY:"arr[i] = callback.call(that, a[i], i, a)",AFTER:"return arr"}),m={},J=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?
"HTML"!==a.nodeName:!1},R=G.test(l.querySelectorAll),S=function(){var a=[],b=document.createElement("div");l.appendChild(b).innerHTML="<a id='jiesa_unique'></a><select id='jiesa_unique-\f]' msallowcapture=''><option selected=''></option></select>";b.querySelectorAll("[msallowcapture^='']").length&&a.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");b.querySelectorAll("[selected]").length||a.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
b.querySelectorAll(":checked").length||a.push(":checked");b.querySelectorAll("[id~=jiesa_unique-]").length||a.push("~=");b.querySelectorAll("a#jiesa_unique+*").length||a.push(".#.+[+~]");return a.length&&new RegExp(a.join("|"))}(),K=!0,B,t=function(a){arguments.length?(K=!1,B=a):B=R&&w.querySelectorAll?function(a,c){return c.querySelectorAll(a)}:function(){throw Error("Jiesa: No selector engine installed");}},C=l.matches||l.webkitMatchesSelector||l.mozMatchesSelector||l.oMatchesSelector||l.msMatchesSelector,
D=G.test(C),T=function(){var a=document.createElement("div");return!!C.call(a,"div")}(),U=function(a,b){return r(a)?function(c){var d,f,g,h,k;if(!D||D&&J(w)){if(K&&(S.test(a)||J(w)))throw Error("Jiesa: This version of querySelectorAll (QSA) are not supported.");g=B(a,b||c.ownerDocument)}for(;c&&1===c.nodeType;c=c.parentNode){if(D&&T)f=C.call(c,a);else for(h=0,k=g.length;h<k;)if(d=g[h++],d===c)return d;if(f||!b||c===b)break}return f&&c}:null},V=function(a,b,c,d,f,g){if("number"===typeof b)return(a=
c["[[__node__]]"])?a[b]:void 0;if(!q){var h=a.ownerDocument.documentElement;if("rightClick"===b)return 3===c.keyCode||2===c.button;if("which"===b)return c.keyCode;if("button"===b)return b=c.button,b&1?1:b&2?3:b&4?2:0;if("pageX"===b)return c.clientX+h.scrollLeft-h.clientLeft;if("pageY"===b)return c.clientY+h.scrollTop-h.clientTop;if("preventDefault"===b)return function(){return c.returnValue=!1};if("stopPropagation"===b)return function(){return c.cancelBubble=!0}}if("type"===b)return d;if("defaultPrevented"===
b)return"defaultPrevented"in c?c.defaultPrevented:!1===c.returnValue;if("target"===b)return f;if("currentTarget"===b)return g;if("relatedTarget"===b)return c.relatedTarget||c[(c.toElement===a?"from":"to")+"Element"];var k=c[b];return y(k)?function(){return k.apply(c,arguments)}:k},W=function(a,b,c,d){r(b)&&(b=a[b]);try{return b.call(a,c,d)}catch(f){return p.setTimeout(function(){throw f;},1),!1}},A=function(a,b,c,d,f,g){var h=U(c,a),k=m[b],n=function(c){c=c||((a.ownerDocument||a.document||a).parentWindow||
p).event;if(A.skip!==b&&("ie8Custom"!==n._type||c.srcUrn===b)){var k=c.target||c.srcElement||a.ownerDocument.documentElement,l=!h||1!==k.nodeType||!0===k.disabled&&"click"===event.type?a:h(k),m=f||[];l&&(1===g&&L(a,b,d),m=f?Q(m,function(d){return V(a,d,c,b,k,l)}):Array.prototype.slice.call(c["[[__node__]]"]||[0],1),b&&!1===d.apply(a,m)&&(q?c.preventDefault():c.returnValue=!1))}};k&&(n=k(n,b)||n);q||"on"+(n._type||b)in a||(n._type="ie8Custom");n.type=b;n.callback=d;n.selector=c;return n},x=function(a,
b,c,d,f,g){if(3!==a.nodeType&&8!==a.nodeType&&b)if(a["[[__event__]]"]||(a["[[__event__]]"]=[]),r(b)){y(d)&&(f=d,r(c)?d=null:(d=c,c=null));y(c)&&(f=c,d=c=null);if(!y(f))return!1;var h=A(a,b,c,f,d,g);h&&(q?a.addEventListener(h._type||b,h,!!h.capture):a.attachEvent("on"+(h._type||b),h));a["[[__event__]]"].push(h)}else null!==b&&"object"===typeof b&&(H(b)?z(b,function(b){g?x(a,b,c,d,f,1):x(a,b,c,d,f)}):(void 0===d&&H(c)&&(d=c,c=void 0),z(Object.keys(b),function(f){g?x(a,f,c,d,b[f],1):x(a,f,c,d,b[f])})))},
L=function(a,b,c,d){if(void 0!==a&&a["[[__event__]]"]&&r(b))return void 0===d&&void 0!==c&&(d=c,c=void 0),P(a["[[__event__]]"],function(f){var g=b!==f.type;if(g=(g=g||c&&c!==f.selector)||d&&d!==f.callback)return!0;b=f._type||f.type;q?a.removeEventListener(b,f,!!f.capture):a.detachEvent("on"+b,f)}),this},u=function(a,b,c){if(!a||3!==a.nodeType&&8!==a.nodeType){var d,f;if(r(b))d=m[b],f={},d&&(f=d(f)||f),f=f._type||b;else return!1;q?(~b.indexOf(":")?(d=new CustomEvent(f,{detail:c,bubbles:!0}),d["[[__node__]]"]=
arguments):(d=a.ownerDocument.createEvent("HTMLEvents"),d["[[__node__]]"]=arguments,d.initEvent(f,!0,!0)),d=a.dispatchEvent(d)):(d=a.ownerDocument.createEventObject(),d["[[__node__]]"]=arguments,"on"+f in a||(f="ie8Custom"),"ie8Custom"===f&&(d.srcUrn=b),a.fireEvent("on"+f,d),d=!1!==d.returnValue);d&&a[b]&&(A.skip=b,W(a,b),A.skip=null);return d}};"onfocusin"in l?(m.focus=function(a){a._type="focusin"},m.blur=function(a){a._type="focusout"}):m.focus=m.blur=function(a){a.capture=!0};w.createElement("input").validity&&
(m.invalid=function(a){a.capture=!0});if(!q){document.attachEvent("onkeydown",function(){var a=p.event,b=a.srcElement,c=b.form;if(c&&"textarea"!==b.type&&13===e.keyCode&&!1!==a.returnValue)return u(c,"submit"),!1});document.attachEvent("onclick",function(){var a=p.event.srcElement,b=a.form,a=a.type;!b||"submit"!==a&&"reset"!==a||u(b,a)});var E=function(){g&&g.value!==v&&(v=g.value,u(g,"input"))},M=function(){g&&g.checked!==v&&(v=g.checked,u(g,"change"))},N=function(){u(g,"change")},g,v;9===document.documentMode&&
document.attachEvent("onselectionchange",E);document.attachEvent("onfocusin",function(){g&&8===document.documentMode&&(g.detachEvent("onclick",M),g.detachEvent("onchange",N),g.detachEvent("onpropertychange",E));g=p.event.srcElement;v=g.value;if(8===document.documentMode){var a=g.type;"checkbox"===a||"radio"===a?(g.attachEvent("onclick",M),v=g.checked):1===g.nodeType&&(g.attachEvent("onchange",N),"text"!==a&&"password"!==a&&"textarea"!==a||g.attachEvent("onpropertychange",E))}})}var X=p.Jiesa,F={on:function(a,
b,c,d,f,g){a=a.length?a:[a];z(a,function(a){x(a,b,c,d,f,g)})},once:function(a,b,c,d,f){return this.on(a,b,c,d,f,1)},off:function(a,b,c,d){a=a.length?a:[a];z(a,function(a){L(a,b,c,d)})},fire:function(a,b,c){a=a.length?a[0]:a;return u(a,b,c)},setSelectorEngine:t,eventHooks:m,noConflict:function(){p.Jiesa===F&&(p.Jiesa=X);return F}};t();p.Jiesa=F})(window);