// Jiesa v 0.0.8a
(function(n,C){var r=document||{},k=r.documentElement||{},p=k.addEventListener,D=/^[^{]+\{\s*\[native \w/,J=/callback\.call\(([^)]+)\)/g,t=function(a){return"string"===typeof a},v=function(a){return"function"===typeof a},E=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},F={BEFORE:"",COUNT:"a ? a.length : 0",BODY:"",AFTER:""},q=function(){return function(a){var b="%BEFORE%\nvar i=0,n=%COUNT%;for(;i<n;++i){%BODY%}%AFTER%",c;for(c in F)b=b.replace("%"+c+"%",a[c]||
F[c]);b=b.replace(J,function(a,b){return"(that?"+a+":callback("+b.split(",").slice(1).join()+"))"});return Function("a","callback","that","undefined",b)}}(),w=q({BODY:"callback.call(that, a[i], i, a)",AFTER:"return a"}),K=q({BEFORE:"var arr = []",BODY:"if (callback.call(that, a[i], i, a)) arr.push(a[i])",AFTER:"return arr"}),L=q({BEFORE:"var arr = Array(a && a.length || 0)",BODY:"arr[i] = callback.call(that, a[i], i, a)",AFTER:"return arr"}),l={},G=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?
"HTML"!==a.nodeName:!1},M=D.test(k.querySelectorAll),N=function(){var a=[],b=document.createElement("div");k.appendChild(b).innerHTML="<a id='jiesa_unique'></a><select id='jiesa_unique-\f]' msallowcapture=''><option selected=''></option></select>";b.querySelectorAll("[msallowcapture^='']").length&&a.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");b.querySelectorAll("[selected]").length||a.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
b.querySelectorAll(":checked").length||a.push(":checked");b.querySelectorAll("[id~=jiesa_unique-]").length||a.push("~=");b.querySelectorAll("a#jiesa_unique+*").length||a.push(".#.+[+~]");return a.length&&new RegExp(a.join("|"))}(),H=!0,y,q=function(a){arguments.length?(H=!1,y=a):y=M&&r.querySelectorAll?function(a,c){return c.querySelectorAll(a)}:function(){throw Error("Jiesa: No selector engine installed");}},z=k.matches||k.webkitMatchesSelector||k.mozMatchesSelector||k.oMatchesSelector||k.msMatchesSelector,
A=D.test(z),O=function(){var a=document.createElement("div");return!!z.call(a,"div")}(),P=function(a,b){return t(a)?function(c){var d,e,g,f,h;if(!A||A&&G(r)){if(H&&(N.test(a)||G(r)))throw Error("Jiesa: This version of querySelectorAll (QSA) are not supported.");g=y(a,b||c.ownerDocument)}for(;c&&1===c.nodeType;c=c.parentNode){if(A&&(O||c.document&&11!==c.document.nodeType))e=z.call(c,a);else for(f=0,h=g.length;f<h;)if(d=g[f++],d===c)return d;if(e||!b||c===b)break}return e&&c}:null},Q=function(a,b,
c,d,e,g){if("number"===typeof a)return(c=b["[[__node__]]"])?c[a]:void 0;if(!p){var f=d.ownerDocument.documentElement;if("rightClick"===a)return 3===b.keyCode||2===b.button;if("which"===a)return b.keyCode;if("button"===a)return a=b.button,a&1?1:a&2?3:a&4?2:0;if("pageX"===a)return b.clientX+f.scrollLeft-f.clientLeft;if("pageY"===a)return b.clientY+f.scrollTop-f.clientTop;if("preventDefault"===a)return function(){return b.returnValue=!1};if("stopPropagation"===a)return function(){return b.cancelBubble=
!0}}if("type"===a)return c;if("defaultPrevented"===a)return"defaultPrevented"in b?b.defaultPrevented:!1===b.returnValue;if("target"===a)return e;if("currentTarget"===a)return g;if("relatedTarget"===a)return b.relatedTarget||b[(b.toElement===d?"from":"to")+"Element"];var h=b[a];return v(h)?function(){return h.apply(b,arguments)}:h},R=function(a,b,c,d){t(b)&&(b=a[b]);try{return b.call(a,c,d)}catch(e){return n.setTimeout(function(){throw e;},1),!1}},x=function(a,b,c,d,e,g){var f=P(c,a),h=l[b],m=function(c){c=
c||((a.ownerDocument||a.document||a).parentWindow||n).event;if(x.skip!==b&&("ie8Custom"!==m._type||c.srcUrn===b)){var h=c.target||c.srcElement||a.ownerDocument.documentElement,k=!f||1!==h.nodeType||!0===h.disabled&&"click"===event.type?a:f(h),l=e||[];k&&(1===g&&I(a,b,d),l=e?L(l,function(d){return Q(d,c,b,a,h,k)}):Array.prototype.slice.call(c["[[__node__]]"]||[0],1),b&&!1===d.apply(a,l)&&(p?c.preventDefault():c.returnValue=!1))}};h&&(m=h(m,b)||m);p||"on"+(m._type||b)in a||(m._type="ie8Custom");m.type=
b;m.callback=d;m.selector=c;return m},u=function(a,b,c,d,e,g){if(3!==a.nodeType&&8!==a.nodeType&&b)if(a["[[__event__]]"]||(a["[[__event__]]"]=[]),"string"===typeof b){v(d)&&(e=d,t(c)?d=null:(d=c,c=null));v(c)&&(e=c,d=c=null);if(!v(e))return!1;var f=x(a,b,c,e,d,g);f&&(p?a.addEventListener(f._type||b,f,!!f.capture):a.attachEvent("on"+(f._type||b),f));a["[[__event__]]"].push(f)}else null!==b&&"object"===typeof b&&(E(b)?w(b,function(b){g?u(a,b,c,d,e,1):u(a,b,c,d,e)}):(d===C&&E(c)&&(d=c,c=void 0),w(Object.keys(b),
function(e){g?u(a,e,c,d,b[e],1):u(a,e,c,d,b[e])})))},I=function(a,b,c,d){if(a!==C&&a["[[__event__]]"]&&t(b))return void 0===d&&void 0!==c&&(d=c,c=void 0),K(a["[[__event__]]"],function(e){var g=b!==e.type;if(g=(g=g||c&&c!==e.selector)||d&&d!==e.callback)return!0;b=e._type||e.type;p?a.removeEventListener(b,e,!!e.capture):a.detachEvent("on"+b,e)}),this},S=function(a,b,c){if(!a||3!==a.nodeType&&8!==a.nodeType){var d,e;if(t(b))d=l[b],e={},d&&(e=d(e)||e),e=e._type||b;else return!1;p?(~b.indexOf(":")?(d=
new CustomEvent(e,{detail:c,bubbles:!0}),d["[[__node__]]"]=arguments):(d=a.ownerDocument.createEvent("HTMLEvents"),d["[[__node__]]"]=arguments,d.initEvent(e,!0,!0)),d=a.dispatchEvent(d)):(d=a.ownerDocument.createEventObject(),d["[[__node__]]"]=arguments,"on"+e in a||(e="ie8Custom"),"ie8Custom"===e&&(d.srcUrn=b),a.fireEvent("on"+e,d),d=!1!==d.returnValue);d&&a[b]&&(x.skip=b,R(a,b),x.skip=null);return d}};"onfocusin"in k?(l.focus=function(a){a._type="focusin"},l.blur=function(a){a._type="focusout"}):
l.focus=l.blur=function(a){a.capture=!0};r.createElement("input").validity&&(l.invalid=function(a){a.capture=!0});var T=n.Jiesa,B={on:function(a,b,c,d,e,g){a=a.length?a:[a];w(a,function(a){u(a,b,c,d,e,g)})},once:function(a,b,c,d,e){return this.on(a,b,c,d,e,1)},off:function(a,b,c,d){a=a.length?a:[a];w(a,function(a){I(a,b,c,d)})},fire:function(a,b,c){a=a.length?a[0]:a;return S(a,b,c)},setSelectorEngine:q,eventHooks:l,noConflict:function(){n.Jiesa===B&&(n.Jiesa=T);return B}};q();n.Jiesa=B})(window);