// Jiesa v 0.0.8a
(function(n,ba){var v=document||{},k=v.documentElement||{},p=k.addEventListener,w=/^[^{]+\{\s*\[native \w/,O=/callback\.call\(([^)]+)\)/g,q=function(a){return"string"===typeof a},z=function(a){return"function"===typeof a},G=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},H={BEFORE:"",COUNT:"a ? a.length : 0",BODY:"",AFTER:""},r=function(){return function(a){var b="%BEFORE%\nvar i=0,n=%COUNT%;for(;i<n;++i){%BODY%}%AFTER%",c;for(c in H)b=b.replace("%"+c+"%",a[c]||
H[c]);b=b.replace(O,function(a,b){return"(that?"+a+":callback("+b.split(",").slice(1).join()+"))"});return Function("a","callback","that","undefined",b)}}(),x=r({BODY:"callback.call(that, a[i], i, a)",AFTER:"return a"}),P=r({BEFORE:"var arr = []",BODY:"if (callback.call(that, a[i], i, a)) arr.push(a[i])",AFTER:"return arr"}),Q=r({BEFORE:"var arr = Array(a && a.length || 0)",BODY:"arr[i] = callback.call(that, a[i], i, a)",AFTER:"return arr"}),l={},I=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?
"HTML"!==a.nodeName:!1},R=w.test(k.querySelectorAll),S=function(){var a=[],b=document.createElement("div");k.appendChild(b).innerHTML="<a id='jiesa_unique'></a><select id='jiesa_unique-\f]' msallowcapture=''><option selected=''></option></select>";b.querySelectorAll("[msallowcapture^='']").length&&a.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");b.querySelectorAll("[selected]").length||a.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
b.querySelectorAll(":checked").length||a.push(":checked");b.querySelectorAll("[id~=jiesa_unique-]").length||a.push("~=");b.querySelectorAll("a#jiesa_unique+*").length||a.push(".#.+[+~]");return a.length&&new RegExp(a.join("|"))}(),J=!0,B,r=function(a){arguments.length?(J=!1,B=a):B=R&&v.querySelectorAll?function(a,c){return c.querySelectorAll(a)}:function(){throw Error("Jiesa: No selector engine installed");}},C=k.matches||k.webkitMatchesSelector||k.mozMatchesSelector||k.oMatchesSelector||k.msMatchesSelector,
D=w.test(C),T=function(){var a=document.createElement("div");return!!C.call(a,"div")}(),U=function(a,b){return q(a)?function(c){var d,e,f,g,h;if(!D||D&&I(v)){if(J&&(S.test(a)||I(v)))throw Error("Jiesa: This version of querySelectorAll (QSA) are not supported.");f=B(a,b||c.ownerDocument)}for(;c&&1===c.nodeType;c=c.parentNode){if(D&&T)e=C.call(c,a);else for(g=0,h=f.length;g<h;)if(d=f[g++],d===c)return d;if(e||!b||c===b)break}return e&&c}:null},V=function(a,b,c,d,e,f){if("number"===typeof b)return(a=
c["[[__node__]]"])?a[b]:void 0;if(!p){var g=a.ownerDocument.documentElement;if("rightClick"===b)return 3===c.keyCode||2===c.button;if("which"===b)return c.keyCode;if("button"===b)return b=c.button,b&1?1:b&2?3:b&4?2:0;if("pageX"===b)return c.clientX+g.scrollLeft-g.clientLeft;if("pageY"===b)return c.clientY+g.scrollTop-g.clientTop;if("preventDefault"===b)return function(){return c.returnValue=!1};if("stopPropagation"===b)return function(){return c.cancelBubble=!0}}if("type"===b)return d;if("defaultPrevented"===
b)return"defaultPrevented"in c?c.defaultPrevented:!1===c.returnValue;if("target"===b)return e;if("currentTarget"===b)return f;if("relatedTarget"===b)return c.relatedTarget||c[(c.toElement===a?"from":"to")+"Element"];var h=c[b];return z(h)?function(){return h.apply(c,arguments)}:h},W=function(a,b,c,d){q(b)&&(b=a[b]);try{return b.call(a,c,d)}catch(e){return n.setTimeout(function(){throw e;},1),!1}},A=function(a,b,c,d,e,f){var g=U(c,a),h=l[b],m=function(c){c=c||((a.ownerDocument||a.document||a).parentWindow||
n).event;if(A.skip!==b&&("ie8Custom"!==m._type||c.srcUrn===b)){var h=c.target||c.srcElement||a.ownerDocument.documentElement,k=!g||1!==h.nodeType||!0===h.disabled&&"click"===event.type?a:g(h),l=e||[];k&&(1===f&&K(a,b,d),l=e?Q(l,function(d){return V(a,d,c,b,h,k)}):Array.prototype.slice.call(c["[[__node__]]"]||[0],1),b&&!1===d.apply(a,l)&&(p?c.preventDefault():c.returnValue=!1))}};h&&(m=h(m,b)||m);p||"on"+(m._type||b)in a||(m._type="ie8Custom");m.type=b;m.callback=d;m.selector=c;return m},y=function(a,
b,c,d,e,f){if(3!==a.nodeType&&8!==a.nodeType&&b)if(a["[[__event__]]"]||(a["[[__event__]]"]=[]),q(b)){z(d)&&(e=d,q(c)?d=null:(d=c,c=null));z(c)&&(e=c,d=c=null);if(!z(e))return!1;var g=A(a,b,c,e,d,f);g&&(p?a.addEventListener(g._type||b,g,!!g.capture):a.attachEvent("on"+(g._type||b),g));a["[[__event__]]"].push(g)}else null!==b&&"object"===typeof b&&(G(b)?x(b,function(b){f?y(a,b,c,d,e,1):y(a,b,c,d,e)}):(void 0===d&&G(c)&&(d=c,c=void 0),x(Object.keys(b),function(e){f?y(a,e,c,d,b[e],1):y(a,e,c,d,b[e])})))},
K=function(a,b,c,d){if(void 0!==a&&a["[[__event__]]"]&&q(b))return void 0===d&&void 0!==c&&(d=c,c=void 0),P(a["[[__event__]]"],function(e){var f=b!==e.type;if(f=(f=f||c&&c!==e.selector)||d&&d!==e.callback)return!0;b=e._type||e.type;p?a.removeEventListener(b,e,!!e.capture):a.detachEvent("on"+b,e)}),this},t=function(a,b,c){if(!a||3!==a.nodeType&&8!==a.nodeType){var d,e;if(q(b))d=l[b],e={},d&&(e=d(e)||e),e=e._type||b;else return!1;p?(~b.indexOf(":")?(d=new CustomEvent(e,{detail:c,bubbles:!0}),d["[[__node__]]"]=
arguments):(d=a.ownerDocument.createEvent("HTMLEvents"),d["[[__node__]]"]=arguments,d.initEvent(e,!0,!0)),d=a.dispatchEvent(d)):(d=a.ownerDocument.createEventObject(),d["[[__node__]]"]=arguments,"on"+e in a||(e="ie8Custom"),"ie8Custom"===e&&(d.srcUrn=b),a.fireEvent("on"+e,d),d=!1!==d.returnValue);d&&a[b]&&(A.skip=b,W(a,b),A.skip=null);return d}};"onfocusin"in k?(l.focus=function(a){a._type="focusin"},l.blur=function(a){a._type="focusout"}):l.focus=l.blur=function(a){a.capture=!0};v.createElement("input").validity&&
(l.invalid=function(a){a.capture=!0});if(!p){var w=document.documentMode,X=9===w,L=8===w,Y=/^(reset|submit)$/,Z=/^(textarea|text|password|file)$/;x(["onkeydown","onmousedown"],function(a){document.attachEvent(a,function(){var a=n.event,c=a.srcElement;if(Z.test(type)&&c.form&&13===a.keyCode&&!1!==a.returnValue)return t(c.form,"submit"),!1})});document.attachEvent("onclick",function(){var a=n.event.srcElement,b=a.type;Y.test(b)&&a.form&&t(a.form,b)});var E=function(){f&&f.value!==u&&(u=f.value,t(f,
"input"))},M=function(){f&&f.checked!==u&&(u=f.checked,t(f,"change"))},N=function(){t(f,"change")},f,u;X&&document.attachEvent("onselectionchange",E);document.attachEvent("onfocusin",function(){f&&L&&(f.detachEvent("onclick",M),f.detachEvent("onchange",N),f.detachEvent("onpropertychange",E));f=n.event.srcElement;u=f.value;if(L){var a=f.type;"checkbox"===a||"radio"===a?(f.attachEvent("onclick",M),u=f.checked):1===f.nodeType&&(f.attachEvent("onchange",N),"text"!==a&&"password"!==a&&"textarea"!==a||
f.attachEvent("onpropertychange",E))}})}var aa=n.Jiesa,F={on:function(a,b,c,d,e,f){a=a.length?a:[a];x(a,function(a){y(a,b,c,d,e,f)})},once:function(a,b,c,d,e){return this.on(a,b,c,d,e,1)},off:function(a,b,c,d){a=a.length?a:[a];x(a,function(a){K(a,b,c,d)})},fire:function(a,b,c){a=a.length?a[0]:a;return t(a,b,c)},setSelectorEngine:r,eventHooks:l,noConflict:function(){n.Jiesa===F&&(n.Jiesa=aa);return F}};r();n.Jiesa=F})(window);